name: Bundle

on:
  workflow_call:
    outputs:
      files:
        description: 'List of artifact filenames.'
        value: |
          ${{ jobs.Bundle.outputs.ubuntu_artifact_filename }}
          ${{ jobs.Bundle.outputs.macos_artifact_filename }}
          ${{ jobs.Bundle.outputs.macos_intel_artifact_filename }}
          ${{ jobs.Bundle.outputs.windows_artifact_filename }}

jobs:
  Bundle:
    name: Bundle
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
            wget_cmd: 'wget'
          - os: 'macos-latest'
            wget_cmd: 'wget'
          - os: 'macos-15-intel'
            wget_cmd: 'wget'
          - os: 'windows-latest'
            wget_cmd: 'C:/msys64/usr/bin/wget.exe'

    runs-on: ${{ matrix.os }}

    outputs:
      ubuntu_artifact_filename: ${{ steps.artifact_id.outputs.ubuntu-latest-name }}
      macos_artifact_filename: ${{ steps.artifact_id.outputs.macos-latest-name }}
      macos_intel_artifact_filename: ${{ steps.artifact_id.outputs.macos-15-intel-name }}
      windows_artifact_filename: ${{ steps.artifact_id.outputs.windows-latest-name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Checkout HyperNav Repository
        uses: actions/checkout@v6
        with:
          repository: OceanOptics/hypernav
          ssh-key: ${{ secrets.HYPERNAV_DEPLOY_KEY }}
          path: optional/hypernav

      - name: Checkout Aquasense Repository
        run: |
          git clone https://bitbucket.csiro.au/scm/aqrs/aquasense.git optional/aquasense

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Download external resources
        shell: bash
        run: |
          WGET='${{ matrix.wget_cmd }}'
          "$WGET" -r -nv -np -R "index.html*" -nH --cut-dirs=4 \
            -P inlinino/resources \
            https://misclab.umeoce.maine.edu/ftp/software/Inlinino/resources/
          "$WGET" -r -nv -np -R "index.html*" -nH --cut-dirs=4 \
            -P optional/hypernav/hypernav \
            https://misclab.umeoce.maine.edu/ftp/software/Inlinino/hypernav/

      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
          pip install optional/hypernav
          pip show hypernav
          pip install optional/aquasense
          pip show aquasense
          pip install pyinstaller==6.*
          pip list
          

      - name: Make Bundle
        run: |
          python make.py

      - name: Get Bundle Name
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == macos-* ]]; then
            BUNDLE_NAME=$(basename bundle/dist/*.app | xargs)
          else
            BUNDLE_NAME=$(ls bundle/dist | xargs)
          fi
          echo "BUNDLE_NAME=${BUNDLE_NAME}" >> "$GITHUB_ENV"

      - name: Zip Bundle
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'bundle/dist/'
          path: '${{ env.BUNDLE_NAME }}'
          filename: '${{ env.BUNDLE_NAME }}.zip'

      - name: Upload Bundle
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: bundle/dist/${{ env.BUNDLE_NAME }}.zip
          if-no-files-found: error
        # Known issue of double zip: https://github.com/actions/upload-artifact/issues/39
        # However, need to zip before upload as too many files to send otherwise (very slow)

      - name: Output Artifact Name
        id: artifact_id
        shell: bash
        run: echo "${{ matrix.os }}-name=${{ env.BUNDLE_NAME }}" >> $GITHUB_OUTPUT
