name: Bundle

on:
  workflow_call:
    outputs:
      files:
        description: 'List of artifact filenames.'
        value: |
          ${{ jobs.Bundle.outputs.ubuntu_artifact_filename }}
          ${{ jobs.Bundle.outputs.macos_artifact_filename }}
          ${{ jobs.Bundle.outputs.windows_artifact_filename }}

jobs:
  Bundle:
    name: Bundle
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-13', 'windows-latest' ]

    runs-on: ${{ matrix.os }}

    outputs:
      ubuntu_artifact_filename: ${{ steps.artifact_id.outputs.ubuntu-latest-name }}
      macos_artifact_filename: ${{ steps.artifact_id.outputs.macos-13-name }}
      windows_artifact_filename: ${{ steps.artifact_id.outputs.windows-latest-name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout HyperNav Repository
        uses: actions/checkout@v4
        with:
          repository: OceanOptics/hypernav
          ssh-key: ${{ secrets.HYPERNAV_DEPLOY_KEY }}
          path: optional/hypernav

      - name: Checkout Aquasense Repository
        run: |
          git clone https://bitbucket.csiro.au/scm/aqrs/aquasense.git optional/aquasense

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Download external resources (Ubuntu & macOS)
        if: (matrix.os == 'ubuntu-latest') || (matrix.os == 'macos-13')
        run: |
          cd inlinino/resources
          wget -r -nv -np -R "index.html*" -nH --cut-dirs=4 https://misclab.umeoce.maine.edu/ftp/software/Inlinino/resources/
          cd -
          cd optional/hypernav/hypernav/
          wget -r -nv -np -R "index.html*" -nH --cut-dirs=4 https://misclab.umeoce.maine.edu/ftp/software/Inlinino/hypernav/
          cd -

      - name: Download external resources (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd inlinino/resources
          C:\msys64\usr\bin\wget.exe -r -nv -np -R "index.html*" -nH --cut-dirs=4 https://misclab.umeoce.maine.edu/ftp/software/Inlinino/resources/
          cd -
          cd optional/hypernav/hypernav/
          C:\msys64\usr\bin\wget.exe -r -nv -np -R "index.html*" -nH --cut-dirs=4 https://misclab.umeoce.maine.edu/ftp/software/Inlinino/hypernav/
          cd -

      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
          pip install optional/hypernav
          pip show hypernav
          pip install optional/aquasense
          pip show aquasense
          pip install pyinstaller==6.*
          pip list
          

      - name: Make Bundle
        run: |
          python make.py

      - name: Get Bundle Name (Ubuntu & Windows)
        if: (matrix.os == 'ubuntu-latest') || (matrix.os == 'windows-latest')
        run: echo "BUNDLE_NAME=$(ls bundle/dist | xargs)" >> $GITHUB_ENV
        shell: bash

      - name: Get Bundle Name (macOS)
        if: matrix.os == 'macos-13'
        run: echo "BUNDLE_NAME=$(basename bundle/dist/*.app | xargs)" >> $GITHUB_ENV

      - name: Zip Bundle
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'bundle/dist/'
          path: '${{ env.BUNDLE_NAME }}'
          filename: '${{ env.BUNDLE_NAME }}.zip'

      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: bundle/dist/${{ env.BUNDLE_NAME }}.zip
          if-no-files-found: error
        # Known issue of double zip: https://github.com/actions/upload-artifact/issues/39
        # However, need to zip before upload as too many files to send otherwise (very slow)

      - name: Output Artifact Name
        id: artifact_id
        shell: bash
        run: echo "${{ matrix.os }}-name=${{ env.BUNDLE_NAME }}" >> $GITHUB_OUTPUT
