name: Release

on:
  workflow_call:
    inputs:
      files:
        description: 'Newline-delimited list of path globs for asset files to upload'
        required: False
        type: string

jobs:

  Release:
    name: Release with Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4

      - name: Extract Git tag and Artifact names
        id: getVariables
        run: |
          GIT_TAG=${GITHUB_REF#refs/*/}
          RELEASE_VERSION=${GIT_TAG#v}
          RELEASE_DATETIME="$(date --utc '+%Y-%m-%d %H:%M:%S')"
          # write to step outputs
          cat >> "$GITHUB_OUTPUT" << EOF
          gitTag=${GIT_TAG}
          version=${RELEASE_VERSION}
          datetime=${RELEASE_DATETIME}
          EOF
          # Multi-line variables
          echo "artifacts<<EOF" >> $GITHUB_OUTPUT
          ls | xargs -n 1 >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.getVariables.outputs.artifacts }}

      - name: Create Release Page
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.getVariables.outputs.artifacts }}
          body: |
            **Automated Release created on: ${{ steps.getVariables.outputs.datetime }}**
  
            # New Features
            * tbd
  
            # Changes
            * tbd
  
            # Bug Fixes
            * tbd
          draft: true
          prerelease: false
